### PR TITLE
Pwm+readability

### LINKED ISSUE #1: Support PWM?
I do not see any way to `analogWrite()`.  Am I wrong?  Why the omission?

### PR DESCRIPTION
**Pull request by mralexgray**
> Would be great if this used registers... but in the meantime is fine.  Wasn't sure if you'd prefer / is even possinble to get PWM state without storing it as a variable, but considering I'm normalizing it, and scaling the analobgWrite, figured this is fine.
> 
> Sorry, cvouldntr resist.  The defines needed alignment so badly.. and the function declarations are much more consice and comprehensible now.  Hoep you agree.

PS: fixes #1

### CODE REVIEW

**Comment by fenichelar** [comment]
Checkout my latest commit, I think it might help ;)

**Comment by mralexgray** [comment]
did that fix spacing?

**Comment by mralexgray** [comment]
that is OK...  leave it to us to define the pin mappings (they already exist for ATTiny)... let me just see that it still works...

**Comment by fenichelar** [comment]
65925bf95ed4f5c6c8a69bb7d02b81a4121ddb31, should work now (I hope)

**Pull request closed without merging**
